Update uni_go_to_pose_clf.py
Before the suggested change, NumPy produces the following error message:

AttributeError: `np.mat` was removed in the NumPy 2.0 release. Use `np.asmatrix` instead.

After the suggested change, the script runs as expected.